# Generated by Django 4.2.10 on 2024-02-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stateApp', '0002_rename_statemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='population',
            field=models.IntegerField(),
        ),
    ]
