# Generated by Django 4.2.10 on 2024-02-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stateApp', '0003_alter_state_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='population',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
